Repository banzzokee/banzzokee-back, pull requests merged in 2024-01, with the labels that each got.

#4 docs: 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/custom.md
Labels: :memo: docs

#6 GitHub Actions CI
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/build.yml
Labels: :bricks: infra, backend

#9 feat: Security default setting
  src/main/java/homes/banzzokee/domain/test/controller/TestController.java
  src/main/java/homes/banzzokee/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feat, backend

#13 feature: setup-user-and-shelter-entity
  src/main/java/homes/banzzokee/domain/common/entity/BaseEntity.java
  src/main/java/homes/banzzokee/domain/shelter/dao/ShelterRepository.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/type/LoginType.java
  src/main/java/homes/banzzokee/domain/type/Role.java
  src/main/java/homes/banzzokee/domain/user/dao/UserRepository.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/global/config/jpa/JpaAuditingConfig.java
  src/main/resources/application-jpa.yml
  src/main/resources/application.yml
  src/main/resources/sql/grant.sql
  src/test/java/homes/banzzokee/BanzzokeeApplicationTests.java
Labels: :sparkles: feat, backend

#10 feature: Exception Handler
  src/main/java/homes/banzzokee/domain/test/controller/TestController.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/error/ErrorResponse.java
  src/main/java/homes/banzzokee/global/error/GlobalExceptionHandler.java
  src/main/java/homes/banzzokee/global/error/exception/CustomException.java
  src/main/resources/application.yml
Labels: :sparkles: feat, backend

#18 feature: setup-s3-and-upload-image
  build.gradle
  src/main/java/homes/banzzokee/domain/common/image/dto/ImageDto.java
  src/main/java/homes/banzzokee/domain/common/image/exception/ImageFailToUploadException.java
  src/main/java/homes/banzzokee/domain/common/image/service/ImageService.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterDto.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/user/controller/UserController.java
  src/main/java/homes/banzzokee/domain/user/dto/UserProfileDto.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/domain/user/exception/UserNotFoundException.java
  src/main/java/homes/banzzokee/domain/user/service/UserService.java
  src/main/java/homes/banzzokee/global/config/s3/S3Configuration.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
  src/test/java/homes/banzzokee/domain/common/image/service/ImageServiceTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
  src/test/resources/application.yml
Labels: :sparkles: feat, :white_check_mark: test, backend

#25 feature: create chat room
  src/main/java/homes/banzzokee/domain/room/controller/ChatRoomController.java
  src/main/java/homes/banzzokee/domain/room/dao/ChatRoomRepository.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatShelterDto.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatUserDto.java
  src/main/java/homes/banzzokee/domain/room/dto/CreateRoomResponse.java
  src/main/java/homes/banzzokee/domain/room/entity/ChatRoom.java
  src/main/java/homes/banzzokee/domain/room/service/ChatRoomService.java
  src/main/resources/application-jpa.yml
  src/test/java/homes/banzzokee/domain/room/controller/ChatRoomControllerTest.java
  src/test/java/homes/banzzokee/domain/room/service/ChatRoomServiceTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
Labels: :sparkles: feat, backend

#32 feature: setup-s3-and-upload-image-for-merge
  build.gradle
  src/main/java/homes/banzzokee/global/config/s3/S3Configuration.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/infra/fileupload/dto/ImageDto.java
  src/main/java/homes/banzzokee/infra/fileupload/exception/FileFailToUploadException.java
  src/main/java/homes/banzzokee/infra/fileupload/service/FileUploadService.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
  src/test/java/homes/banzzokee/infra/fileupload/service/FileUploadServiceTest.java
  src/test/java/homes/banzzokee/infra/fileupload/service/LocalStackTestContainersTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#30 feature: follow and unfollow user
  src/main/java/homes/banzzokee/domain/user/controller/UserController.java
  src/main/java/homes/banzzokee/domain/user/dao/FollowRepository.java
  src/main/java/homes/banzzokee/domain/user/dto/FollowDto.java
  src/main/java/homes/banzzokee/domain/user/entity/Follow.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/domain/user/exception/CanFollowOnlyShelterUserException.java
  src/main/java/homes/banzzokee/domain/user/exception/CanNotFollowSelfException.java
  src/main/java/homes/banzzokee/domain/user/service/UserService.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/test/java/homes/banzzokee/domain/room/controller/ChatRoomControllerTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#26 feature: set stomp config
  src/main/java/homes/banzzokee/domain/chat/controller/ChatMessageController.java
  src/main/java/homes/banzzokee/domain/chat/controller/MessageController.java
  src/main/java/homes/banzzokee/domain/chat/dao/ChatMessageRepository.java
  src/main/java/homes/banzzokee/domain/chat/dto/MessageDto.java
  src/main/java/homes/banzzokee/domain/chat/dto/SendChatDto.java
  src/main/java/homes/banzzokee/domain/chat/entity/ChatMessage.java
  src/main/java/homes/banzzokee/domain/chat/service/ChatMessageService.java
  src/main/java/homes/banzzokee/domain/type/MessageType.java
  src/main/java/homes/banzzokee/global/config/stomp/StompWebSocketConfig.java
Labels: :sparkles: feat, backend

#38 feature: setup adoptions
  src/main/java/homes/banzzokee/domain/adoption/dao/AdoptionRepository.java
  src/main/java/homes/banzzokee/domain/adoption/dto/AdoptionResponse.java
  src/main/java/homes/banzzokee/domain/adoption/dto/RegisterAdoptionRequest.java
  src/main/java/homes/banzzokee/domain/adoption/dto/UpdateAdoptionRequest.java
  src/main/java/homes/banzzokee/domain/adoption/entity/Adoption.java
  src/main/java/homes/banzzokee/domain/type/AdoptionStatus.java
  src/main/java/homes/banzzokee/domain/type/BreedType.java
  src/main/java/homes/banzzokee/domain/type/DogGender.java
  src/main/java/homes/banzzokee/domain/type/DogSize.java
  src/main/java/homes/banzzokee/global/validator/BreedValidator.java
  src/main/java/homes/banzzokee/global/validator/DateValidator.java
  src/main/java/homes/banzzokee/global/validator/DogGenderValidator.java
  src/main/java/homes/banzzokee/global/validator/DogSizeValidator.java
  src/main/java/homes/banzzokee/global/validator/annotation/BreedValid.java
  src/main/java/homes/banzzokee/global/validator/annotation/DateValid.java
  src/main/java/homes/banzzokee/global/validator/annotation/DogGenderValid.java
  src/main/java/homes/banzzokee/global/validator/annotation/DogSizeValid.java
Labels: :sparkles: feat, backend

#48 feature: verify auth
  src/main/java/homes/banzzokee/domain/auth/config/MailConfig.java
  src/main/java/homes/banzzokee/domain/auth/controller/AuthController.java
  src/main/java/homes/banzzokee/domain/auth/dto/EmailDto.java
  src/main/java/homes/banzzokee/domain/auth/dto/EmailVerifyDto.java
  src/main/java/homes/banzzokee/domain/auth/dto/SignupDto.java
  src/main/java/homes/banzzokee/domain/auth/exception/EmailCodeInvalidException.java
  src/main/java/homes/banzzokee/domain/auth/exception/EmailCodeUnmatchedException.java
  src/main/java/homes/banzzokee/domain/auth/service/AuthService.java
  src/main/java/homes/banzzokee/global/config/redis/RedisConfig.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/util/redis/RedisService.java
  src/main/resources/application-redis.yml
  src/main/resources/application-smtp.yml
  src/main/resources/application.yml
  src/test/java/homes/banzzokee/domain/auth/controller/AuthControllerTest.java
  src/test/java/homes/banzzokee/domain/auth/service/AuthServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#49 feature: nickname check auth
  src/main/java/homes/banzzokee/domain/auth/controller/AuthController.java
  src/main/java/homes/banzzokee/domain/auth/service/AuthService.java
  src/main/java/homes/banzzokee/domain/user/dao/UserRepository.java
  src/test/java/homes/banzzokee/domain/auth/controller/AuthControllerTest.java
  src/test/java/homes/banzzokee/domain/auth/service/AuthServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#47 feature: send verify auth
  src/main/java/homes/banzzokee/domain/auth/dto/EmailDto.java
  src/main/java/homes/banzzokee/domain/auth/service/AuthService.java
  src/test/java/homes/banzzokee/domain/auth/controller/AuthControllerTest.java
  src/test/java/homes/banzzokee/domain/auth/service/AuthServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#54 feature: 특정 유저에게만 채팅메세지 전송
  src/main/java/homes/banzzokee/domain/chat/controller/MessageController.java
  src/main/java/homes/banzzokee/domain/chat/service/ChatMessageService.java
  src/main/java/homes/banzzokee/global/config/stomp/StompWebSocketConfig.java
  src/main/java/homes/banzzokee/global/config/stomp/exception/SocketException.java
  src/main/java/homes/banzzokee/global/config/stomp/handler/CustomHandshakeHandler.java
  src/main/java/homes/banzzokee/global/config/stomp/principal/StompPrincipal.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/error/GlobalExceptionHandler.java
Labels: :sparkles: feat, backend

#64 feature: delete shelter
  src/main/java/homes/banzzokee/domain/room/dao/ChatRoomRepository.java
  src/main/java/homes/banzzokee/domain/room/entity/ChatRoom.java
  src/main/java/homes/banzzokee/domain/shelter/controller/ShelterController.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/shelter/service/ShelterService.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/test/java/homes/banzzokee/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/homes/banzzokee/domain/shelter/service/ShelterServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
Labels: :recycle: refactor, :sparkles: feat, :white_check_mark: test, backend

#63 feature: update shelter
  src/main/java/homes/banzzokee/domain/room/dao/ChatRoomRepository.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatShelterDto.java
  src/main/java/homes/banzzokee/domain/room/entity/ChatRoom.java
  src/main/java/homes/banzzokee/domain/shelter/controller/ShelterController.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterDto.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateRequest.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateResponse.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/shelter/service/ShelterService.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/error/exception/NoAuthorizedException.java
  src/test/java/homes/banzzokee/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/homes/banzzokee/domain/shelter/service/ShelterServiceTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockDataUtil.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#60 feature: verify shelter
  src/main/java/homes/banzzokee/domain/room/dao/ChatRoomRepository.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatShelterDto.java
  src/main/java/homes/banzzokee/domain/room/entity/ChatRoom.java
  src/main/java/homes/banzzokee/domain/shelter/controller/ShelterController.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterDto.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateRequest.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateResponse.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/shelter/exception/ShelterAlreadyVerifiedException.java
  src/main/java/homes/banzzokee/domain/shelter/exception/ShelterNotFoundException.java
  src/main/java/homes/banzzokee/domain/shelter/service/ShelterService.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/error/exception/NoAuthorizedException.java
  src/test/java/homes/banzzokee/domain/room/service/ChatRoomServiceTest.java
  src/test/java/homes/banzzokee/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/homes/banzzokee/domain/shelter/service/ShelterServiceTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockDataUtil.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
  src/test/java/homes/banzzokee/infra/fileupload/service/LocalStackTestContainersTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#58 feature: register shelter
  src/main/java/homes/banzzokee/domain/room/dao/ChatRoomRepository.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatShelterDto.java
  src/main/java/homes/banzzokee/domain/room/entity/ChatRoom.java
  src/main/java/homes/banzzokee/domain/shelter/controller/ShelterController.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterDto.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterRegisterRequest.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateRequest.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterUpdateResponse.java
  src/main/java/homes/banzzokee/domain/shelter/entity/Shelter.java
  src/main/java/homes/banzzokee/domain/shelter/exception/NotVerifiedShelterExistsException.java
  src/main/java/homes/banzzokee/domain/shelter/exception/ShelterAlreadyVerifiedException.java
  src/main/java/homes/banzzokee/domain/shelter/exception/ShelterNotFoundException.java
  src/main/java/homes/banzzokee/domain/shelter/exception/UserAlreadyRegisterShelterException.java
  src/main/java/homes/banzzokee/domain/shelter/service/ShelterService.java
  src/main/java/homes/banzzokee/domain/user/entity/User.java
  src/main/java/homes/banzzokee/global/error/ErrorCode.java
  src/main/java/homes/banzzokee/global/error/exception/NoAuthorizedException.java
  src/main/java/homes/banzzokee/global/validator/PasswordValidator.java
  src/main/java/homes/banzzokee/global/validator/constant/RegexPattern.java
  src/main/java/homes/banzzokee/infra/fileupload/dto/ImageDto.java
  src/test/java/homes/banzzokee/domain/room/service/ChatRoomServiceTest.java
  src/test/java/homes/banzzokee/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/homes/banzzokee/domain/shelter/service/ShelterServiceTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockDataUtil.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
  src/test/java/homes/banzzokee/infra/fileupload/service/LocalStackTestContainersTest.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#65 feature: setup elasticsearch for merge
  docker/elasticsearch/elasticsearch-install.sh
  docker/elasticsearch/es.env
  src/main/java/homes/banzzokee/domain/adoption/dto/AdoptionResponse.java
  src/main/java/homes/banzzokee/domain/adoption/dto/RegisterAdoptionRequest.java
  src/main/java/homes/banzzokee/domain/adoption/dto/UpdateAdoptionRequest.java
  src/main/java/homes/banzzokee/domain/adoption/elasticsearch/dao/AdoptionSearchRepository.java
  src/main/java/homes/banzzokee/domain/adoption/elasticsearch/document/AdoptionDocument.java
  src/main/java/homes/banzzokee/domain/adoption/elasticsearch/testcontroller/Test.java
  src/main/java/homes/banzzokee/domain/auth/dto/EmailDto.java
  src/main/java/homes/banzzokee/domain/auth/dto/EmailVerifyDto.java
  src/main/java/homes/banzzokee/domain/auth/dto/SignupDto.java
  src/main/java/homes/banzzokee/domain/chat/dto/MessageDto.java
  src/main/java/homes/banzzokee/domain/chat/dto/SendChatDto.java
  src/main/java/homes/banzzokee/domain/chat/service/ChatMessageService.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatShelterDto.java
  src/main/java/homes/banzzokee/domain/room/dto/ChatUserDto.java
  src/main/java/homes/banzzokee/domain/room/dto/CreateRoomResponse.java
  src/main/java/homes/banzzokee/domain/shelter/dto/ShelterDto.java
  src/main/java/homes/banzzokee/domain/shelter/service/ShelterService.java
  src/main/java/homes/banzzokee/domain/type/FilePath.java
  src/main/java/homes/banzzokee/domain/type/S3Object.java
  src/main/java/homes/banzzokee/domain/user/dto/ChangePasswordRequest.java
  src/main/java/homes/banzzokee/domain/user/dto/ChangePasswordResponse.java
  src/main/java/homes/banzzokee/domain/user/dto/FollowDto.java
  src/main/java/homes/banzzokee/domain/user/dto/WithdrawUserRequest.java
  src/main/java/homes/banzzokee/domain/user/dto/WithdrawUserResponse.java
  src/main/java/homes/banzzokee/domain/user/service/UserService.java
  src/main/java/homes/banzzokee/global/config/elasticsearch/ElasticSearchConfig.java
  src/main/java/homes/banzzokee/infra/fileupload/dto/FileDto.java
  src/main/java/homes/banzzokee/infra/fileupload/service/FileUploadService.java
  src/main/resources/application-elasticsearch.yml
  src/main/resources/application.yml
  src/main/resources/elasticsearch/adoption-mapping.json
  src/main/resources/elasticsearch/adoption-setting.json
  src/test/java/homes/banzzokee/domain/auth/controller/AuthControllerTest.java
  src/test/java/homes/banzzokee/domain/shelter/service/ShelterServiceTest.java
  src/test/java/homes/banzzokee/domain/user/controller/UserControllerTest.java
  src/test/java/homes/banzzokee/domain/user/service/UserServiceTest.java
  src/test/java/homes/banzzokee/infra/fileupload/service/FileUploadServiceTest.java
  src/test/java/homes/banzzokee/infra/fileupload/service/LocalStackTestContainersTest.java
Labels: :recycle: refactor, :sparkles: feat, backend

#75 feature: register fcm token
  src/main/java/homes/banzzokee/domain/notification/controller/NotificationController.java
  src/main/java/homes/banzzokee/domain/notification/dao/FcmTokenRepository.java
  src/main/java/homes/banzzokee/domain/notification/dto/FcmTokenRegisterRequest.java
  src/main/java/homes/banzzokee/domain/notification/entity/FcmToken.java
  src/main/java/homes/banzzokee/domain/notification/service/NotificationService.java
  src/test/java/homes/banzzokee/domain/notification/controller/NotificationControllerTest.java
  src/test/java/homes/banzzokee/domain/notification/service/NotificationServiceTest.java
  src/test/java/homes/banzzokee/global/util/MockMvcUtil.java
Labels: :sparkles: feat, :white_check_mark: test, backend

#68 refactor: setup elasticsearch
  docker/elasticsearch/elasticsearch-install.sh
  src/main/java/homes/banzzokee/global/config/elasticsearch/ElasticSearchConfig.java
  src/main/resources/application-elasticsearch.yml
Labels: :recycle: refactor, backend

#76 chore: queryDSL configuration
  .gitignore
  build.gradle
  src/main/java/homes/banzzokee/global/config/querydsl/QueryDSLConfig.java
Labels: :wrench: chore, backend
